[package]
name = "producer"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.17.0"
toml = "*"
# For examples
env_logger = "0.9"
hex-literal = "0.3"
async-trait = "*"
# Tokio
tokio = {version = "1.0", features=["full"]}